name: flutter_kookminpt_sample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  dio: ^5.3.2
  http: ^1.1.0
  get_it: ^7.2.0
  awesome_dio_interceptor: ^1.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  auto_route: ^7.8.3
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^7.0.8
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/pretendard_thin.otf
          weight: 100
        - asset: assets/font/pretendard_extralight.otf
          weight: 200
        - asset: assets/font/pretendard_light.otf
          weight: 300
        - asset: assets/font/pretendard_regular.otf
          weight: 400
        - asset: assets/font/pretendard_medium.otf
          weight: 500
        - asset: assets/font/pretendard_semibold.otf
          weight: 600
        - asset: assets/font/pretendard_bold.otf
          weight: 700
        - asset: assets/font/pretendard_extrabold.otf
          weight: 800
        - asset: assets/font/pretendard_black.otf
          weight: 900